export const callsData = [
    {
        id: "CLL001",
        call: "Long",
        name: "Reliance EQ",
        segment:"Equity",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "21-Oct-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        id: "CLL002",
        call: "Short",
        name: "HDFC EQ",
        segment:"Equity",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Oct-2024, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        id: "CLL003",
        call: "Long",
        name: "Axis Bank EQ",
        segment:"Equity",
        version: "2",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Nov-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Failed",
    },
    {
        id: "CLL004",
        call: "Short",
        name: "ICICI Bank EQ",
        segment:"Options",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "09-Jan-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        id: "CLL005",
        call: "Long",
        name: "Nifty 22500 CE",
        segment:"Options",
        version: "2",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "20-Feb-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Failed",
    },
    {
        id: "CLL006",
        call: "Long",
        name: "Nifty 22500 CE",
        segment:"Options",
        version: "2",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Nov-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Inactive",
    },
    {
        id: "CLL007",
        call: "Short",
        name: "BankNifty 48500",
        segment:"Options",
        version: "1",
        entryprice: 105.00,
        targetprice: "138.00",
        stoploss: "88.00",
        riskratio: "1:2.0",
        timedate: "12-Mar-2025, 09:30 AM",
        validity: "Intraday",
        shared: "120",
        status: "Hit",
    },
    {
        id: "CLL008",
        call: "Long",
        name: "Silver MAR",
        segment:"Commodity",
        version: "2",
        entryprice: 84.50,
        targetprice: "115.00",
        stoploss: "72.00",
        riskratio: "1:2.1",
        timedate: "18-Mar-2025, 10:05 AM",
        validity: "Intraday",
        shared: "95",
        status: "Failed",
    },
    {
        id: "CLL009",
        call: "Short",
        name: "Sensex 75500 PE",
        segment:"Equity",
        version: "1",
        entryprice: 110.00,
        targetprice: "145.00",
        stoploss: "94.00",
        riskratio: "1:2.3",
        timedate: "25-Apr-2025, 09:20 AM",
        validity: "Intraday",
        shared: "150",
        status: "Hit",
    },
    {
        id: "CLL010",
        call: "Long",
        name: "Gold APR",
        segment:"Commodity",
        version: "1",
        entryprice: 78.00,
        targetprice: "105.00",
        stoploss: "65.00",
        riskratio: "1:2.0",
        timedate: "02-May-2025, 09:40 AM",
        validity: "Intraday",
        shared: "80",
        status: "Failed",
    },
    {
        id: "CLL011",
        call: "Short",
        name: "Reliance Features",
        segment:"Futures",
        version: "3",
        entryprice: 132.00,
        targetprice: "170.00",
        stoploss: "112.00",
        riskratio: "1:1.9",
        timedate: "14-Jun-2025, 09:35 AM",
        validity: "Intraday",
        shared: "200",
        status: "Inactive",
    },
    {
        id: "CLL012",
        call: "Long",
        name: "ICICI Bank",
        segment:"Features",
        version: "1",
        entryprice: 96.00,
        targetprice: "128.00",
        stoploss: "82.00",
        riskratio: "1:2.2",
        timedate: "03-Jul-2025, 09:25 AM",
        validity: "Intraday",
        shared: "110",
        status: "Hit",
    },
    {
        id: "CLL013",
        call: "Short",
        name: "Crud Oil FEB",
        segment:"Commodity",
        version: "2",
        entryprice: 101.00,
        targetprice: "135.00",
        stoploss: "86.00",
        riskratio: "1:2.1",
        timedate: "19-Aug-2025, 09:50 AM",
        validity: "Intraday",
        shared: "140",
        status: "Hit",
    },
    {
        id: "CLL014",
        call: "Long",
        name: "Natural Gas FEB",
        segment:"Commodity",
        version: "1",
        entryprice: 89.00,
        targetprice: "118.00",
        stoploss: "74.00",
        riskratio: "1:2.0",
        timedate: "11-Sep-2025, 09:15 AM",
        validity: "Intraday",
        shared: "90",
        status: "Failed",
    },

]






export const clientsData = [
    {
        id: "CL0001233",
        name: "Ethereal Design",
        status: "Active",
        riskScore: 39,
        riskCategory: "Rathi",
        email: "daniel@untitledui.com",
        phone: "+91 65432 10987",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Chennai",
        state:"TamilNadu",
        kycvalidated:"Yes",
        occupation:"IT Professional",
        income:"75,00,000",
        age:"34"
        
    },
    {
        id: "CL0001234",
        name: "Olivia Rhye",
        status: "Active",
        riskScore: 30,
        riskCategory: "Rathi",
        email: "olivia@untitledui.com",
        phone: "+91 86574 79856",
        dob:"21/12/2021",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Mumbai",
        state:"Maharashtra",
        kycvalidated:"Yes",
        },
    {
        id: "CL0001235",
        name: "Ethan Hunt",
        status: "Review",
        riskScore: 45,
        riskCategory: "AtiRathi",
        email: "ethan@untitledui.com",
        phone: "+91 96574 29845",
        dob:"02/08/2013",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Trivandrum",
        state:"Kerala",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001236",
        name: "Sophia Turner",
        status: "KYC Pending",
        riskScore: 28,
        riskCategory: "Rathi",
        email: "sophia@untitledui.com",
        phone: "+91 87564 19854",
        dob:"05/02/2007",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Pune",
        state:"Maharashtra",
        kycvalidated:"No",
    },
    {
        id: "CL0001237",
        name: "Liam Smith",
        status: "Risk Profile",
        riskScore: 35,
        riskCategory: "Rathi",
        email: "liam@untitledui.com",
        phone: "+91 76584 78901",
        dob:"30/05/1995",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Kochi",
        state:"Kerala",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001238",
        name: "Emma Johnson",
        status: "Active",
        riskScore: 32,
        riskCategory: "AtiRathi",
        email: "emma@untitledui.com",
        phone: "+91 65473 45678",
        dob:"16/03/1999",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"KanyaKumari",
        state:"TamilNadu",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001239",
        name: "Noah Brown",
        status: "Review",
        riskScore: 41,
        riskCategory: "AtiRathi",
        email: "noah@untitledui.com",
        phone: "+91 54321 67890",
        dob:"12/01/1987",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Agra",
        state:"UttarPradesh",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001240",
        name: "Ava Wilson",
        status: "KYC Pending",
        riskScore: 27,
        riskCategory: "Rathi",
        email: "ava@untitledui.com",
        phone: "+91 43210 12345",
        dob:"19/09/1970",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Jaipur",
        state:"Rajasthan",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001241",
        name: "Mason Davis",
        status: "Inactive",
        riskScore: 38,
        riskCategory: "AtiRathi",
        email: "mason@untitledui.com",
        phone: "+91 32109 34567",
        dob:"14/09/1980",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Mumbai",
        state:"Maharashtra",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001242",
        name: "Isabela Moore",
        status: "Risk Profile",
        riskScore: 29,
        riskCategory: "Rathi",
        email: "isabella@untitledui.com",
        phone: "+91 21098 76543",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Trivandrum",
        state:"Kerala",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001243",
        name: "James Taylor",
        status: "Active",
        riskScore: 37,
        riskCategory: "Rathi",
        email: "james@untitledui.com",
        phone: "+91 10987 65432",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Hydrabad",
        state:"Telangana",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001244",
        name: "Mia Anderson",
        status: "KYC Pending",
        riskScore: 33,
        riskCategory: "Rathi",
        email: "mia@untitledui.com",
        phone: "+91 98765 43210",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Bangalore",
        state:"Karnataka",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001245",
        name: "Alexander Thomas",
        status: "Inactive",
        riskScore: 42,
        riskCategory: "Rathi",
        email: "alexander@untitledui.com",
        phone: "+91 87654 32109",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Mysore",
        state:"Karnataka",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001246",
        name: "Charlotte White",
        status: "Active",
        riskScore: 31,
        riskCategory: "Rathi",
        email: "charlotte@untitledui.com",
        phone: "+91 99887 66554",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Coimbatore",
        state:"TamilNadu",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001247",
        name: "Benjamin Harris",
        status: "Review",
        riskScore: 46,
        riskCategory: "AtiRathi",
        email: "benjamin@untitledui.com",
        phone: "+91 88776 55443",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Pallakad",
        state:"Kerala",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001248",
        name: "Amelia Clark",
        status: "KYC Pending",
        riskScore: 26,
        riskCategory: "Rathi",
        email: "amelia@untitledui.com",
        phone: "+91 77665 44332",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"NewDelhi",
        state:"Delhi",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001249",
        name: "Henry Lewis",
        status: "Risk Profile",
        riskScore: 40,
        riskCategory: "AtiRathi",
        email: "henry@untitledui.com",
        phone: "+91 66554 33221",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Varanasi",
        state:"UttarPradesh",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001250",
        name: "Evelyn Walker",
        status: "Active",
        riskScore: 34,
        riskCategory: "Rathi",
        email: "evelyn@untitledui.com",
        phone: "+91 55443 22110",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Amritsar",
        state:"Punjab",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001251",
        name: "Daniel Martinez",
        status: "Inactive",
        riskScore: 44,
        riskCategory: "AtiRathi",
        email: "daniel.m@untitledui.com",
        phone: "+91 44332 11099",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Shimla",
        state:"HimachalPradesh",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001252",
        name: "Harper Robinson",
        status: "Review",
        riskScore: 36,
        riskCategory: "Rathi",
        email: "harper@untitledui.com",
        phone: "+91 33221 00988",
        dob:"09/03/2003",
        gender:"Female",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Udaipur",
        state:"Rajasthan",
        kycvalidated:"Yes",
    },
    {
        id: "CL0001253",
        name: "Sebastian Young",
        status: "KYC Pending",
        riskScore: 29,
        riskCategory: "Rathi",
        email: "sebastian@untitledui.com",
        phone: "+91 22110 99877",
        dob:"09/03/2003",
        gender:"Male",
        lastlogin:"09/03/2025",
        lastcall:"09/03/2025",
        city:"Mumbai",
        state:"Maharashtra",
        kycvalidated:"Yes",
    },
    
    
]
