export const callsData = [
    {
        call: "Buy",
        name: "Sensex 82500 CE",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "21-Oct-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        call: "Sell",
        name: "Sensex 98500 CE",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Oct-2024, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        call: "Buy",
        name: "Sensex 84500 CE",
        version: "2",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Nov-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Failed",
    },
    {
        call: "Sell",
        name: "Sensex 32500 CE",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "09-Jan-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Hit",
    },
    {
        call: "Buy",
        name: "Sensex 72500 CE",
        version: "1",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "20-Feb-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Failed",
    },
    {
        call: "Buy",
        name: "Sensex 68500 CE",
        version: "2",
        entryprice: 92.00,
        targetprice: "120.00",
        stoploss: "78.00",
        riskratio: "1:2.2",
        timedate: "06-Nov-2025, 09:25 AM",
        validity: "Intraday",
        shared: "100",
        status: "Inactive",
    },
]






export const clientsData = [
    {
        id: "CL0001247",
        name: "Ethereal Design",
        status: "Active",
        riskScore: 39,
        riskCategory: "Rathi",
        email: "daniel@untitledui.com",
        phone: "+91 65432 10987",
    },
    {
        id: "CL0001234",
        name: "Olivia Rhye",
        status: "Active",
        riskScore: 30,
        riskCategory: "Rathi",
        email: "olivia@untitledui.com",
        phone: "+91 86574 79856",
    },
    {
        id: "CL0001235",
        name: "Ethan Hunt",
        status: "Review",
        riskScore: 45,
        riskCategory: "AtiRathi",
        email: "ethan@untitledui.com",
        phone: "+91 96574 29845",
    },
    {
        id: "CL0001236",
        name: "Sophia Turner",
        status: "KYC Pending",
        riskScore: 28,
        riskCategory: "Rathi",
        email: "sophia@untitledui.com",
        phone: "+91 87564 19854",
    },
    {
        id: "CL0001237",
        name: "Liam Smith",
        status: "Risk Profile",
        riskScore: 35,
        riskCategory: "Rathi",
        email: "liam@untitledui.com",
        phone: "+91 76584 78901",
    },
    {
        id: "CL0001238",
        name: "Emma Johnson",
        status: "Active",
        riskScore: 32,
        riskCategory: "AtiRathi",
        email: "emma@untitledui.com",
        phone: "+91 65473 45678",
    },
    {
        id: "CL0001239",
        name: "Noah Brown",
        status: "Review",
        riskScore: 41,
        riskCategory: "AtiRathi",
        email: "noah@untitledui.com",
        phone: "+91 54321 67890",
    },
    {
        id: "CL0001240",
        name: "Ava Wilson",
        status: "KYC Pending",
        riskScore: 27,
        riskCategory: "Rathi",
        email: "ava@untitledui.com",
        phone: "+91 43210 12345",
    },
    {
        id: "CL0001241",
        name: "Mason Davis",
        status: "Inactive",
        riskScore: 38,
        riskCategory: "AtiRathi",
        email: "mason@untitledui.com",
        phone: "+91 32109 34567",
    },
    {
        id: "CL0001242",
        name: "Isabella Moore",
        status: "Risk Profile",
        riskScore: 29,
        riskCategory: "Rathi",
        email: "isabella@untitledui.com",
        phone: "+91 21098 76543",
    },
    {
        id: "CL0001243",
        name: "James Taylor",
        status: "Active",
        riskScore: 37,
        riskCategory: "Rathi",
        email: "james@untitledui.com",
        phone: "+91 10987 65432",
    },
    {
        id: "CL0001244",
        name: "Mia Anderson",
        status: "KYC Pending",
        riskScore: 33,
        riskCategory: "Rathi",
        email: "mia@untitledui.com",
        phone: "+91 98765 43210",
    },
    {
        id: "CL0001245",
        name: "Alexander Thomas",
        status: "Inactive",
        riskScore: 42,
        riskCategory: "Rathi",
        email: "alexander@untitledui.com",
        phone: "+91 87654 32109",
    },
]
